spring:
  config:
    activate:
      on-profile: prod

  # Production Database Configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:prod_db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Usually validate in prod
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Documentation is enabled globally in application.yaml, 
# but we can explicitly ensure it's on here as well if needed.
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
